name: build-binary

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            artifact: zeth-rpc-proxy-linux-amd64
          - os: macos-latest
            target: aarch64-apple-darwin
            artifact: zeth-rpc-proxy-macos-arm64
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: install rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: build zeth-rpc-proxy
        run: cargo build --release -p zeth-rpc-proxy --target ${{ matrix.target }}

      - name: upload binary
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact }}
          path: target/${{ matrix.target }}/release/zeth-rpc-proxy
